name: Release CI

on:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  build:
    name: Build boot.3dsx
    uses: ./.github/workflows/build.yaml
  publish_release:
    name: Publish release archive
    needs: build
    runs-on: ubuntu-latest
    env:
      VERSTRING: ${{ needs.build.outputs.VERSTRING }}
    steps:
    - name: Download cacert.pem
      run: mkdir -p config/ssl && curl -sSfL "https://curl.se/ca/cacert.pem" -o config/ssl/cacert.pem
    - name: Download build artifact from previous job
      uses: actions/download-artifact@v4
      with:
        name: 3ds-hbmenu-${{ env.VERSTRING }}
    - name: Bundle release archive
      run: zip "3ds-hbmenu-$VERSTRING.zip" -r config boot.3dsx
    - name: Publish release archive
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "dev"
        prerelease: true
        title: "Latest commit"
        files: |
          "./3ds-hbmenu-${{ env.VERSTRING }}.zip"
